language: go
go:
  - 1.6
  - 1.7beta1

# first part of the GOARCH workaround
# setting the GOARCH directly doesn't work, since the value will be overwritten later
# so set it to a temporary environment variable first
env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  # - GIMME_OS=linux GIMME_ARCH=386

# second part of the GOARCH workaround
# now actually set the GOARCH env variable to the value of the temporary variable set earlier
before_install:
  # - export GOARCH=$TRAVIS_GOARCH
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/mattn/goveralls
  - go env # for debugging

install:
  - go get github.com/gordonklaus/ineffassign

script:
  - go get -t ./...
  # - ineffassign .
  # - ginkgo -cover -r
  - go test -coverprofile=coverage.out -covermode=set
  - cd frames && go test -coverprofile=coverage.out -covermode=set && cd ..

after_success:
  # - cat quic-go.coverprofile > coverage.txt
  # - cat */*.coverprofile | grep -v "mode: atomic" >> coverage.txt
  - .travis/after_success.sh

  # - bash <(curl -s https://codecov.io/bash) -f coverage.txt
  - goveralls -coverprofile=coverage.txt -service=travis-ci
