version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: 0
  matrix:
    - GOARCH: 386
    - GOARCH: amd64

clone_folder: c:\gopath\src\github.com\marten-seemann\quic-go

install:
  - set PATH=%PATH%;%GOPATH%\bin
  - echo %PATH%
  - echo %GOPATH%
  - git submodule update --init --recursive
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - rm -r integrationtests
  - go test ./... --ginkgo.noColor
  # - ginkgo -noColor -skipPackage integrationtests

test: off

deploy: off
