version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: 0

clone_folder: c:\gopath\src\github.com\marten-seemann\quic-go

install:
  - echo %PATH%
  - echo %GOPATH%
  - git submodule update --init --recursive
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test ./... --ginkgo.noColor

test: off

deploy: off
