defaults: &defaults
  working_directory: /go/src/github.com/marten-seemann/quic-go
  steps:
    - checkout
    - run:
        name: "Setup build environment"
        command: |
          go get -t ./...
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega
          echo 127.0.0.1 quic.clemente.io | sudo tee -a /etc/hosts
    - run: 
        name: "Build infos"
        command: |
          echo $GOARCH
          go version
          google-chrome --version
          printf "quic.clemente.io certificate valid until: " && openssl x509 -in example/fullchain.pem -enddate -noout | cut -d = -f 2
    - run: 
        name: "Run benchmark tests"
        command: ginkgo -randomizeAllSpecs -randomizeSuites -trace benchmark -- -samples=1
    - run: 
        name: "Run benchmark tests"
        command: ginkgo -randomizeAllSpecs -randomizeSuites -trace benchmark -- -samples=1
    - run: 
        name: "Run benchmark tests with race detector"
        command: ginkgo -race -randomizeAllSpecs -randomizeSuites -trace benchmark -- -samples=1 -size=10
    - run:
        name: "Run integration tests"
        command: ginkgo -r -v -randomizeAllSpecs -randomizeSuites -trace integrationtests

version: 2
jobs:
  build-go1.10:
    docker:
      - image: circleci/golang:1.10.2-stretch-browsers
    <<: *defaults
  build-go1.9:
    docker:
      - image: circleci/golang:1.9.6-stretch-browsers
    <<: *defaults
workflows:
  version: 2
  build:
    jobs:
      - build-go1.9
      - build-go1.10
